version: '3.8'

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_KEY=base64:1TFKSH/GOy7ftDEV76P0juhrRj208MuPM9lVwNvI6rc=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - DB_CONNECTION=mysql
            - DB_HOST=monorail.proxy.rlwy.net
            - DB_PORT=43924
            - DB_DATABASE=railway
            - DB_USERNAME=root
            - DB_PASSWORD=CCXVPgEFXNqHmEbmKEcmnvpJMbewtONQ
            - SWOOLE_TASK_WORKER_NUM=100
            - SWOOLE_TASK_MAX_REQUEST=1000
            - OCTANE_TASK_TIMEOUT=10
        depends_on:
            - mysql

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: railway
            MYSQL_ROOT_PASSWORD: CCXVPgEFXNqHmEbmKEcmnvpJMbewtONQ
        volumes:
            - ./mysql_data:/var/lib/mysql
